### ISSUE TITLE
squash not working on minikube or openshift

### ISSUE THREAD

**Issue by dwojciec** [solo-io/squash#15]
I tried to install squash on Openshift and I'm facing issue. I decided to install it on minikube just to compare but I'm facing same issue.
On minikube 

```
$ kubectl get pod
NAME                                READY     STATUS    RESTARTS   AGE
example-service1-7895445947-24fn6   1/1       Running   0          41m
example-service2-7998cc5dd6-vc9jb   1/1       Running   0          40m
hello-minikube-57889c865c-tpsqs     1/1       Running   0          56m
squash-client-8qsx6                 1/1       Running   0          50m
squash-server-569d564b64-xbc4q      1/1       Running   0          51m
```

```
$ kubectl log squash-server-569d564b64-xbc4q 
W1221 11:13:33.680285   87652 cmd.go:361] log is DEPRECATED and will be removed in a future version. Use logs instead.
2017/12/21 09:21:48 Serving squash at http://[::]:8080
time="2017-12-21T09:24:18Z" level=info msg="GetDebugAttachmentsHandler called!" 
time="2017-12-21T09:24:48Z" level=debug msg="GetDebugAttachmentsHandler timing out!" 
time="2017-12-21T09:24:49Z" level=info msg="GetDebugAttachmentsHandler called!" 
time="2017-12-21T09:25:19Z" level=debug msg="GetDebugAttachmentsHandler timing out!" 
```

```
$ kubectl log squash-client-8qsx6 
W1221 11:14:12.720956   87898 cmd.go:361] log is DEPRECATED and will be removed in a future version. Use logs instead.
time="2017-12-21T09:24:18Z" level=info msg="bridge started" 
time="2017-12-21T09:24:18Z" level=info msg="Squash Client started" 
time="2017-12-21T09:24:18Z" level=info msg=handleAttachment server="http://10.105.215.107:80" 
time="2017-12-21T09:24:18Z" level=debug msg="creating client" cfg="&{10.105.215.107:80 /api/v2 [http]}" 
time="2017-12-21T09:24:18Z" level=debug msg="watchForAttached - calling PopContainerToDebug" params="&{<nil> [] 0xc42000fc80 0xc42000fc90 0xc42037f5ec 30000000000 <nil> <nil>}" 
time="2017-12-21T09:24:48Z" level=warning msg="watchForAttached - error calling function:" err="context deadline exceeded" 
```

$  squash --url=http://127.0.0.1:8080/v2/api list attachments
panic: unknown error (status 404): {resp:0xc4200f4480} 

goroutine 1 [running]:
main.listattachments(0xc420308fc0, 0x0, 0x0)
	/home/yuval/go/src/github.com/solo-io/squash/cmd/squash-cli/list.go:70 +0x326
main.init.3.func1(0xc420365680, 0xc420308f80, 0x1, 0x2, 0x0, 0x0)
	/home/yuval/go/src/github.com/solo-io/squash/cmd/squash-cli/list.go:45 +0xca
github.com/solo-io/squash/vendor/github.com/spf13/cobra.(*Command).execute(0xc420365680, 0xc420308f40, 0x2, 0x2, 0xc420365680, 0xc420308f40)
	/home/yuval/go/src/github.com/solo-io/squash/vendor/github.com/spf13/cobra/command.go:649 +0x456
github.com/solo-io/squash/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x29968c0, 0x0, 0x20a4184, 0x12)
	/home/yuval/go/src/github.com/solo-io/squash/vendor/github.com/spf13/cobra/command.go:728 +0x2fe
github.com/solo-io/squash/vendor/github.com/spf13/cobra.(*Command).Execute(0x29968c0, 0x29c96fd, 0x2096145)
	/home/yuval/go/src/github.com/solo-io/squash/vendor/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/yuval/go/src/github.com/solo-io/squash/cmd/squash-cli/main.go:47 +0x115
```





On my Openshift installation 
I pasted a part of my squash-server pod 
```

2017/12/21 09:04:49 Serving squash at http://[::]:8080
--
  | time="2017-12-21T09:04:51Z" level=info msg="GetDebugAttachmentsHandler called!"
  | time="2017-12-21T09:04:51Z" level=info msg="GetDebugAttachmentsHandler called!"
  | time="2017-12-21T09:04:51Z" level=info msg="GetDebugAttachmentsHandler called!"
  | time="2017-12-21T09:04:52Z" level=info msg="GetDebugAttachmentsHandler called!"
  | time="2017-12-21T09:05:21Z" level=debug msg="GetDebugAttachmentsHandler timing out!"
  | time="2017-12-21T09:05:21Z" level=debug msg="GetDebugAttachmentsHandler timing out!"

```

example of the log of a squash-client (I have 3 nodes and the log are the same)
```

time="2017-12-21T02:26:26Z" level=warning msg="watchForAttached - error calling function:" err="context deadline exceeded"
--
  | time="2017-12-21T02:26:27Z" level=debug msg="watchForAttached - calling PopContainerToDebug" params="&{<nil> [] 0xc4203feb50 0xc4203feb60 0xc420418090 30000000000 <nil> <nil>}"
  | time="2017-12-21T02:26:57Z" level=warning msg="watchForAttached - error calling function:" err="context deadline exceeded"
  | time="2017-12-21T02:26:58Z" level=debug msg="watchForAttached - calling PopContainerToDebug" params="&{<nil> [] 0xc420434670 0xc420434680 0xc42020c03c 30000000000 <nil> <nil>}"
  | time="2017-12-21T02:27:28Z" level=warning msg="watchForAttached - error calling function:" err="context deadline exceeded"
```

Any help are welcome.

**Comment by yuval-k** [comment]
@dwojciec  my first suspect would be a version issue - as we recently change the api verion of squash.
The logs from the client and server look ok (the timeouts are normal part of a long-poll).
The command line client seems to be using the old api -  Can you please download the latest squash command line client (release 0.2) and try again? 

see here: https://github.com/solo-io/squash/releases/tag/v0.2.0

**Comment by ilevine** [comment]
@dwojciec does it work for you after upgrading the client installation ? can I close the issue ?

**Comment by dwojciec** [comment]
@yuval-k @ilevine when I did my test december 19th and I'm using squash on OSX and I tested it on linux box too. The version mentionned into your email is dated from December 7th. It's the version I used on OSX and Linux. (a 'squash -v for version' command would be an added value.).

**Comment by dwojciec** [comment]
@yuval-k @ilevine my problem seems to be the usage of squash. Now on my OSX by executing 
```
$ squash --url=http://squash-server-squash.apps.<MYDOMAIN>/api/v2  list attachments
State |ID |Debugger |Image |Debugger Address
```
but by checking the log of the squash server when I'm trying to attach a pod it seems the pod has to be located on the 'default' project. 
see command 
```
squash --url=http://squash-server-squash.apps.<MYDOMAIN>/api/v2 debug-container docker-registry-default.apps.<MYDOMAIN>/squash/microservice:latest  microservice-1-gcb4w microservice dlv
Failed adding container - check parameter names match container on the platform. error: [POST /debugattachment][404] addDebugAttachmentNotFound 
```

the content of the squash-server log 
```

time="2018-01-08T14:49:22Z" level=info msg="DebugattachmentAddDebugAttachmentHandler called!"
--
  | time="2018-01-08T14:49:22Z" level=info msg="Trying to locate" podname=microservice-1-gcb4w
  | time="2018-01-08T14:49:22Z" level=warning msg="Locate - can't locate pod microservice-1-gcb4wUser \"system:serviceaccount:squash:squash-server\" cannot get pods in project \"default\""
  | time="2018-01-08T14:49:22Z" level=warning msg="DebugattachmentAddDebugAttachmentHandler can't locate container" error="User \"system:serviceaccount:squash:squash-server\" cannot get pods in project \"default\""
```
squash command is looking for a pod inside project called default even I'm located inside the project called squash.
To continue my tests I will create the microservice pod inside project called default to see if I'm able to attach to it.

**Comment by yuval-k** [comment]
We actually releasing new version squash that supports debugging pods in different namespaces - and hopefully that will help. 
If you still encounter ping me on our slack (http://slack.solo.io/ to get an invite automatically) and I will be happy to assist.
