### ISSUE TITLE
`squash wait` doesn't return the debug server

### ISSUE THREAD

**Issue by philloooo** [solo-io/squash#50]
`squash wait` says the debug session started, but doesn't actually display the debug server
```
phillis@cdistest_admin:~$ ./squash  --url=http://localhost:8001/api/v1/namespaces/squash/services/squash-server:http-squash-api/proxy/api/v2 debug-container --namespace phillis quay.io/cdis/arborist:master arborist-deployment-6fdbff5584-fq469  arborist dlv 
Debug config id: n6iXAnV0mB
phillis@cdistest_admin:~$ ./squash  --url=http://localhost:8001/api/v1/namespaces/squash/services/squash-server:http-squash-api/proxy/api/v2 wait n6iXAnV0mB
Debug session started! debug server is at: 
```

Here is the server log:
```
 kubectl logs --tail 10 squash-server-8b7fd89bf-hpdqx --namespace=squash
time="2018-08-02T22:58:41Z" level=debug msg="GetDebugAttachmentsHandler timing out!"
time="2018-08-02T22:58:41Z" level=info msg="GetDebugAttachmentsHandler called!"
time="2018-08-02T22:58:42Z" level=debug msg="GetDebugAttachmentsHandler timing out!"
ERROR: logging before flag.Parse: E0802 22:58:42.070772       1 reflector.go:205] github.com/solo-io/squash/pkg/platforms/kubernetes/crd/client/informers/externalversions/factory.go:60: Failed to list *v1.DebugRequest: debugrequests.squash.solo.io is forbidden: User "system:serviceaccount:squash:squash-server" cannot list debugrequests.squash.solo.io at the cluster scope
ERROR: logging before flag.Parse: E0802 22:58:42.071743       1 reflector.go:205] github.com/solo-io/squash/pkg/platforms/kubernetes/crd/client/informers/externalversions/factory.go:60: Failed to list *v1.DebugAttachment: debugattachments.squash.solo.io is forbidden: User "system:serviceaccount:squash:squash-server" cannot list debugattachments.squash.solo.io at the cluster scope
time="2018-08-02T22:58:42Z" level=info msg="GetDebugAttachmentsHandler called!"
time="2018-08-02T22:58:42Z" level=info msg="GetDebugAttachmentsHandler called!"
time="2018-08-02T22:58:43Z" level=info msg="GetDebugAttachmentsHandler called!"
ERROR: logging before flag.Parse: E0802 22:58:43.072202       1 reflector.go:205] github.com/solo-io/squash/pkg/platforms/kubernetes/crd/client/informers/externalversions/factory.go:60: Failed to list *v1.DebugRequest: debugrequests.squash.solo.io is forbidden: User "system:serviceaccount:squash:squash-server" cannot list debugrequests.squash.solo.io at the cluster scope
ERROR: logging before flag.Parse: E0802 22:58:43.073201       1 reflector.go:205] github.com/solo-io/squash/pkg/platforms/kubernetes/crd/client/informers/externalversions/factory.go:60: Failed to list *v1.DebugAttachment: debugattachments.squash.solo.io is forbidden: User "system:serviceaccount:squash:squash-server" cannot list debugattachments.squash.solo.io at the cluster scope
```

**Comment by sandyydk** [comment]
SANDYYDK-M-V0ME:src sandyydk$ ./squash --url=http://SQUASH-SERVER-ADDRESS/api/v2 list attachments
panic: Get http://SQUASH-SERVER-ADDRESS/api/v2/debugattachment?wait=false: dial tcp: lookup SQUASH-SERVER-ADDRESS on 72.163.128.140:53: no such host

goroutine 1 [running]:
main.listattachments(0xc4203968c0, 0x0, 0x0)
	/go/src/github.com/solo-io/squash/cmd/squash-cli/list.go:70 +0x326
main.init.3.func1(0xc420201200, 0xc420396820, 0x1, 0x2, 0x0, 0x0)
	/go/src/github.com/solo-io/squash/cmd/squash-cli/list.go:45 +0xca
github.com/solo-io/squash/vendor/github.com/spf13/cobra.(*Command).execute(0xc420201200, 0xc4203967e0, 0x2, 0x2, 0xc420201200, 0xc4203967e0)
	/go/src/github.com/solo-io/squash/vendor/github.com/spf13/cobra/command.go:649 +0x456
github.com/solo-io/squash/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x29958c0, 0x0, 0x20a4996, 0x12)
	/go/src/github.com/solo-io/squash/vendor/github.com/spf13/cobra/command.go:728 +0x2fe
github.com/solo-io/squash/vendor/github.com/spf13/cobra.(*Command).Execute(0x29958c0, 0x29c86fd, 0x2096946)
	/go/src/github.com/solo-io/squash/vendor/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/go/src/github.com/solo-io/squash/cmd/squash-cli/main.go:47 +0x115
SANDYYDK-M-V0ME:src sandyydk$ ./squash --url=http:// 172.17.0.6/api/v2 list attachments
Error: unknown command "172.17.0.6/api/v2" for "squash"
Run 'squash --help' for usage.
2018/08/06 15:07:06 unknown command "172.17.0.6/api/v2" for "squash"
SANDYYDK-M-V0ME:src sandyydk$ ./squash --url=http://172.17.0.6/api/v2 list attachments
panic: context deadline exceeded

goroutine 1 [running]:
main.listattachments(0xc4202eeb80, 0x0, 0x0)
	/go/src/github.com/solo-io/squash/cmd/squash-cli/list.go:70 +0x326
main.init.3.func1(0xc420317440, 0xc4202eeb40, 0x1, 0x2, 0x0, 0x0)
	/go/src/github.com/solo-io/squash/cmd/squash-cli/list.go:45 +0xca
github.com/solo-io/squash/vendor/github.com/spf13/cobra.(*Command).execute(0xc420317440, 0xc4202eeac0, 0x2, 0x2, 0xc420317440, 0xc4202eeac0)
	/go/src/github.com/solo-io/squash/vendor/github.com/spf13/cobra/command.go:649 +0x456
github.com/solo-io/squash/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x29958c0, 0x0, 0x20a4996, 0x12)
	/go/src/github.com/solo-io/squash/vendor/github.com/spf13/cobra/command.go:728 +0x2fe
github.com/solo-io/squash/vendor/github.com/spf13/cobra.(*Command).Execute(0x29958c0, 0x29c86fd, 0x2096946)
	/go/src/github.com/solo-io/squash/vendor/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/go/src/github.com/solo-io/squash/cmd/squash-cli/main.go:47 +0x115
SANDYYDK-M-V0ME:src sandyydk$

**Comment by sandyydk** [comment]
I see this on kubectl proxy command 

F0806 15:37:15.715395   10814 proxy.go:155] listen tcp 127.0.0.1:8001: bind: address already in use

Found out it's being used by vcom-tunnel...
